### ISSUE TITLE
How to combine the alignment result of BWA and STAR?

### ISSUE THREAD

**Issue by ZHIDIHUAYUAN** [caochch/RICpipe#7]
Hi,
Thanks for your work! I met a question. In your article, you wrote that all the mapped reads from STAR and bwa alignments were combined for the subsequent chimeric read analysis using the RICpipe software. You filted the secondary alignment, but I have no idea about how to deal with the Supplementary Alignment of the alignment of bwa. Did you use option -M to flag shorter split hits as secondary? 

Thank you.

**Comment by ZHIDIHUAYUAN** [comment]
I'm also not sure why you need to use STAR to align first and unmapped reads were aligned again with bwa.

**Comment by caochch** [comment]
Because STAR tolerates reads with a mismatch at the spliced junction sites (i.e., linear mapping)
BUT has a low tolerate rate for reads with a mismatch at the chimeric junction sites (i.e., invert mapping). For this part of reads, I used bwa to further detect chimeric junctions.

For Supplementary Alignment,

**Comment by ZHIDIHUAYUAN** [comment]
Thank you !
In my result, there is a cluster that the left arm overlaps the right arm. 
"chr12   8053387 8053492 chr12   8053466 8053492 FianlCluster_57"
Does this mean there is something wrong with my program?
